[build-system]
requires = ['setuptools>=42.0', "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests"
    ]
[project]
readme="README.md"
maintainers=[{name="Ravi"}]

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true